{% set version = "5.8" %}

package:
  name: pyro5
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/Pyro5/Pyro5-{{ version }}.tar.gz
  sha256: 8ad9cd203c96142542898e66316e068d066d49cb75bda497deea145f7d0f76df

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - pyro5-ns = Pyro5.nameserver:main
    - pyro5-nsc = Pyro5.nsc:main
    - pyro5-echoserver = Pyro5.utils.echoserver:main
    - pyro5-check-config = Pyro5.configure:dump
    - pyro5-httpgateway = Pyro5.utils.httpgateway:main


requirements:
  host:
    - pip
    - python >=3.0
    - setuptools
    - serpent >=1.27
    
  run:
    - python >=3.0
    - serpent >=1.27

test:
  imports:
    - Pyro5
    - Pyro5.compatibility
    - Pyro5.utils

  commands:
    - pyro5-ns --help
    - pyro5-nsc --help
    - pyro5-echoserver --help
    - pyro5-check-config --help
    - pyro5-httpgateway --help

about:
  home: https://pyro5.readthedocs.io
  license: MIT
  license_file: LICENSE
  summary: 'Distributed object middleware for Python (RPC)'

extra:
  recipe-maintainers:
    - irmen
