travis:
  secure:
    BINSTAR_TOKEN: DvT+C8kMjNFD+z33QMt/YUHeUN1xemmBjue2k5D3JOMwrDxmOM6As0UMwbYyo/CasohGyEN1AxafJ1eRzA3NbtrHUhwjjKU2OKdfNnKKsmAM0nTviYOuHpKcDTt8/5NRGVIQ6eGC9n767+kIy0krW8IF7k811tkYbyFAzGC4DRfrLyCk+/uaZ+0mg1HtvAMXG/pWBPejpR0PsaMXC/jZr3z33URZPtWuIgN4DFXHbD99fv2IYMHUZdWsgmVMkqeaCV/1/O2Ud8HEb3zD/ND3JWPhoBUX+Bvn25/oQ6QJ1dFfwXVP3YTP/AN7aeZ/kfYR5S1Z6HrMkCYjfSHTul0wSfUMS9zua1TfeIOqt3e+mcEiTMmNgtS+VI0j8Z6x6fQmuuFuGc9KWCSAahEM2g7CxPf48qYCh29h1cmTzn7A80EIEQiVDBLOZP1AyZA66UC3sA9Q8IuylLv1yRkNG26RH6kwwzABuwQYPV+z55nzoW793t2c1Qzei9gcYJVivX0o+Ic5lV6L6cWqCsX5WVl9BEo3QfjiSO3XtrnL55SQ+7wzw9oV0nQOyN9zZmE+oR/i5zZZQIzjAmRsrwoc2zdBY7acsdDSBr7SZEfcNxgEAbKUfSVaATAMfhPH0dv809KaIn8CF6VufT1X60dtu3f3sY/7msit9Bm6Yym6/vEuBAQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
